### ISSUE TITLE
[Question] Greengrass v2

### ISSUE THREAD

**Issue by bakeruk** [aws/aws-greengrass-core-sdk-js#21]
Is this the correct SDK for Greengrass v2?

If so can someone point me to the documentation on how to get this installed on a core device, please? Greengrass v2 has a different folder structure so any docs that I have come across do not help (mainly because they are intended for GG v1).

Cheer 👍🏼

**Comment by MikeDombo** [comment]
Hi,
This is not the SDK for V2. Please see our [IPC docs](https://docs.aws.amazon.com/greengrass/v2/developerguide/interprocess-communication.html) for a guide to using the SDK. Since you posted in this JavaScript SDK I assume that you want a JS version, however V2 does not yet have a SDK for JavaScript; only Python and Java.

**Comment by bakeruk** [comment]
@MikeDombo Cheers for the confirmation.
